version: 1.0.{build}

branches:
  only:
    - ^master$

image: Visual Studio 2015

clone_depth: 50

environment:
  nodejs_version: "12"

install:
  - ps: Install-Product node $env:nodejs_version
  - sh: curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - cmd: yarn install --colors=always

build:
  verbosity: minimal
