language: node_js

os:
 - linux
 - osx

# Use Java 8
osx_image: xcode9.3

node_js:
  - '10'
  - '6'

matrix:
  exclude:
    - os: osx
      node_js: '10'
    - os: linux
      node_js: '6'

cache:
  yarn: true
  directories:
    - $HOME/.m2

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"
  - if [ $TRAVIS_EVENT_TYPE = "cron" ]; then
      export COMPILER_NIGHTLY=1;
      cd compiler && git fetch && git checkout master;
      cd ..;
    fi

before_script: yarn run build

script: yarn test
